CREATE TABLE EMPLOYEE (
    SSN INT PRIMARY KEY,
    Fname VARCHAR(50),
    Lname VARCHAR(50),
    Gender CHAR(1),
    super_id INT,
    BD DATE,
    DNUM INT,
    FOREIGN KEY (super_id) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (DNUM) REFERENCES DEPT(DNUM)
);

CREATE TABLE DEPT (
    DNUM INT PRIMARY KEY,
    SSN INT,
    HIREDATE DATE,
    DN VARCHAR(100),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE LOC (
    DNUM INT,
    LOC VARCHAR(100),
    PRIMARY KEY (DNUM, LOC),
    FOREIGN KEY (DNUM) REFERENCES DEPT(DNUM)
);

CREATE TABLE PROJECT (
    PNUM INT PRIMARY KEY,
    PN VARCHAR(100),
    LOC VARCHAR(100),
    CITY VARCHAR(100),
    DNUM INT,
    FOREIGN KEY (DNUM) REFERENCES DEPT(DNUM)
);

CREATE TABLE WORK (
    SSN INT,
    PNUM INT,
    hours DECIMAL(5,2),
    PRIMARY KEY (SSN, PNUM),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNUM) REFERENCES PROJECT(PNUM)
);

CREATE TABLE dependent (
    DNUM INT,
    BD DATE,
    GENDER CHAR(1),
    SSN INT,
    PRIMARY KEY (DNUM, SSN),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
);